package ru.lds.telegram.enums;

public enum BotStateEnum {
    START,
    SETTINGS_PROFILE,
    CHECK_ORDER,
    CHECK_SUBSCRIBE,
    CHOOSE_PAYMENT_SYSTEM,
    CHOOSE_ASSET,
    CHOOSE_EXCHANGE,
    CHOOSE_PRICE,
    CHOOSE_TRADE_TYPE,
    ACTION_EXCHANGE,
    ACTION_SUBSCRIBE,
    ACTION_PROFILE,
    ACTION_PAYMENT_SYSTEM,
    ACTION_LIMIT
}
