package ru.lds.telegram.enums;

public enum BotState {
    START,
    PAYMENT_SYSTEM,
    ASSET,
    EXCHANGE,
    PRICE,
    TRADE_TYPE,
    CHECK_COST,
    SUBSCRIBE_COST,
    SUBSCRIBES,
    START_DELETE_SUBSCRIBE,
    DELETE_SUBSCRIBE,
    CHECK_EXCHANGES,
    ACTION_EXCHANGES,
    MY_EXCHANGES,
    MY_PAYMENT_SYSTEMS,
    CHECK_PAYMENT_SYSTEMS,
    ADD_MY_EXCHANGES,
    DELETE_MY_EXCHANGES,
    DELETE_ALL_MY_EXCHANGES,
    ACTION_PAYMENT_SYSTEMS,
    ADD_MY_PAYMENT_SYSTEMS,
    CHECK_SUBSCRIBES, ACTION_SUBSCRIBES, DELETE_MY_PAYMENT_SYSTEMS
}
