package ru.lds.telegram.enums;

public enum BotState {
    START,
    PAYMENT_SYSTEM,
    ASSET,
    EXCHANGE,
    PRICE,
    TRADE_TYPE,
    CHECK_COST,
    DELETE_SUBSCRIBE,
    ACTION_MY_EXCHANGES,
    CHECK_SUBSCRIBES,
    ACTION_SUBSCRIBES,
    SETTINGS_PROFILE,
    ACTION_PROFILE,
    ACTION_MY_PAYMENT_SYSTEM,
    ACTION_MY_LIMITS,
    DELETE_MY_PAYMENT_SYSTEMS
}
