CREATE TABLE public.exchange
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_exchange PRIMARY KEY (id)
);

ALTER TABLE public.exchange
    OWNER TO lds;

CREATE TABLE public.limits
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    volume BIGINT,
    CONSTRAINT pk_limits PRIMARY KEY (id)
);

ALTER TABLE public.limits
    OWNER TO lds;

CREATE TABLE public.orders
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset                  VARCHAR(255),
    date                   TIMESTAMP(6),
    exchange               VARCHAR(255),
    fiat                   VARCHAR(255),
    price                  DOUBLE PRECISION,
    success_orders         BIGINT,
    success_orders_percent DOUBLE PRECISION,
    tradable_quantity      DOUBLE PRECISION,
    trade_method           VARCHAR(255),
    trade_type             VARCHAR(255),
    trans_amount_min       DOUBLE PRECISION,
    trans_amount_max       DOUBLE PRECISION,
    user_name              VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE public.orders
    OWNER TO lds;

CREATE TABLE public.orders_subscribe
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset            VARCHAR(255),
    date             TIMESTAMP(6),
    exchange         VARCHAR(255),
    payment_system   VARCHAR(255),
    price            DOUBLE PRECISION,
    trade_type       VARCHAR(255),
    user_id          BIGINT,
    trans_amount_min DOUBLE PRECISION,
    CONSTRAINT pk_orders_subscribe PRIMARY KEY (id)
);

ALTER TABLE public.orders_subscribe
    OWNER TO lds;

CREATE TABLE public.payment_system
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_payment_system PRIMARY KEY (id)
);

ALTER TABLE public.payment_system
    OWNER TO lds;

CREATE TABLE public.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       TIMESTAMP(6),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    user_id    BIGINT,
    user_name  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE public.users
    OWNER TO lds;

CREATE TABLE public.exchange_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exchange_id BIGINT
                CONSTRAINT fkcu44f7wobmn8salg7m19hch8i
                REFERENCES public.exchange,
    user_id     BIGINT
                CONSTRAINT fk54ew43s4lwrljvrrcitntjjaa
                REFERENCES public.users,
    CONSTRAINT pk_exchange_user PRIMARY KEY (id)
);

ALTER TABLE public.exchange_user
    OWNER TO lds;

CREATE TABLE public.limit_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    limit_id BIGINT
             CONSTRAINT fk1r8uvsgtvqoo0g7jfsq16sknl
             REFERENCES public.limits,
    user_id  BIGINT
             CONSTRAINT fk6vkcucecy4by2usamavl6va9i
             REFERENCES public.users,
    CONSTRAINT pk_limit_user PRIMARY KEY (id)
);

ALTER TABLE public.limit_user
    OWNER TO lds;

CREATE TABLE public.payment_system_user
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_system_id BIGINT
                      CONSTRAINT fk8xgt8sb4l8krwboo3relh1c75
                      REFERENCES public.payment_system,
    user_id           BIGINT
                      CONSTRAINT fkif7candymm6600538b22vygsu
                      REFERENCES public.users,
    CONSTRAINT pk_payment_system_user PRIMARY KEY (id)
);

alter table public.payment_system_user
    owner to lds;

-- Inserts
INSERT INTO public.exchange(name)
VALUES ('Binance'),
       ('Huobi');

INSERT INTO public.payment_system(name)
VALUES ('Tinkoff'),
       ('SberBank'),
       ('RaiffeisenBank'),
       ('Payeer'),
       ('Qiwi');

INSERT INTO public.limits(volume)
VALUES (20000),
       (50000),
       (75000),
       (100000);
-- Admin
INSERT INTO users(date, first_name, last_name, user_id, user_name)
VALUES (now(), 'Дмитрий','Лебедев', 1350257666, 'DmitriyL15');

INSERT INTO limit_user(limit_id, user_id)
VALUES (1, 1);